import { FoodListModel } from "@/models/food.model";

export const carbList: FoodListModel[] = [
  {
    id: "1",
    category: "glucide",
    fat: 3,
    protein: 8,
    carbs: 50,
    name: "Riz complet",
  },
  {
    id: "2",
    category: "glucide",
    fat: 3,
    protein: 8,
    carbs: 50,
    name: "Pâtes complètes",
  },
  {
    id: "3",
    category: "glucide",
    fat: 3,
    protein: 8,
    carbs: 50,
    name: "Semoule",
  },
  {
    id: "4",
    category: "glucide",
    fat: 3,
    protein: 8,
    carbs: 50,
    name: "Boulgour",
  },
  {
    id: "5",
    category: "glucide",
    fat: 3,
    protein: 8,
    carbs: 50,
    name: "Quinoa",
  },
  {
    id: "6",
    category: "glucide",
    fat: 3,
    protein: 8,
    carbs: 50,
    name: "Pommes de terre",
  },
  {
    id: "7",
    category: "glucide",
    fat: 3,
    protein: 8,
    carbs: 50,
    name: "Patate douce",
  },
  {
    id: "8",
    category: "glucide",
    fat: 3,
    protein: 8,
    carbs: 50,
    name: "Pain complet",
  },
  {
    id: "9",
    category: "glucide",
    fat: 3,
    protein: 8,
    carbs: 50,
    name: "Muesli bio",
  },
];
