import { FoodListModel } from "@/models/food.model";

export const fatList: FoodListModel[] = [
  {
    id: "1",
    category: "lipide",
    fat: 40,
    carbs: 35,
    protein: 5,
    name: "Amandes",
  },
  {
    id: "2",
    category: "lipide",
    fat: 40,
    carbs: 35,
    protein: 5,
    name: "Noix de cajou",
  },
  {
    id: "3",
    category: "lipide",
    fat: 40,
    carbs: 35,
    protein: 5,
    name: "Noisette",
  },
  {
    id: "4",
    category: "lipide",
    fat: 40,
    carbs: 35,
    protein: 5,
    name: "Beurre de cacahuète",
  },
  {
    id: "5",
    category: "lipide",
    fat: 40,
    carbs: 35,
    protein: 5,
    name: "Purée d'amandes",
  },
  {
    id: "6",
    category: "lipide",
    fat: 40,
    carbs: 35,
    protein: 5,
    name: "Huile d'olive",
  },
  {
    id: "7",
    category: "lipide",
    fat: 40,
    carbs: 35,
    protein: 5,
    name: "Huile de coco",
  },
  {
    id: "8",
    category: "lipide",
    fat: 40,
    carbs: 35,
    protein: 5,
    name: "Avocat",
  },
];
