import { FoodListModel } from "@/models/food.model";

export const proteinList: FoodListModel[] = [
  {
    category: "proteine",
    fat: 5,
    protein: 20,
    carbs: 15,
    id: 1,
    name: "Blanc de poulet",
  },
  {
    category: "proteine",
    fat: 5,
    protein: 20,
    carbs: 15,
    id: 2,
    name: "Jambon",
  },
  {
    category: "proteine",
    fat: 5,
    protein: 20,
    carbs: 15,
    id: 3,
    name: "Steak haché 5%",
  },
  {
    category: "proteine",
    fat: 5,
    protein: 20,
    carbs: 15,
    id: 4,
    name: "Oeufs",
  },
  {
    category: "proteine",
    fat: 5,
    protein: 20,
    carbs: 15,
    id: 5,
    name: "Poisson",
  },
  {
    category: "proteine",
    fat: 5,
    protein: 20,
    carbs: 15,
    id: 6,
    name: "Crustacés",
  },
  {
    category: "proteine",
    fat: 5,
    protein: 20,
    carbs: 15,
    id: 7,
    name: "Thon conserve",
  },
  {
    category: "proteine",
    fat: 5,
    protein: 20,
    carbs: 15,
    id: 8,
    name: "Tofu",
  },
  {
    category: "proteine",
    fat: 5,
    protein: 20,
    carbs: 15,
    id: 9,
    name: "Fromage blanc",
  },
];
