import { WorkoutSubjectEnum } from "@/models/reducer.model";
import { WorkoutModel } from "@/models/workout.model";

export const workouts: WorkoutModel[] = [
  {
    id: 1,
    title: "Course",
    tags: [WorkoutSubjectEnum.course, WorkoutSubjectEnum.debutant],
    slug: "course",
    content: "<div>Course fractionnée</div>",
  },
  {
    id: 2,
    title: "Course",
    tags: [WorkoutSubjectEnum.course, WorkoutSubjectEnum.debutant],
    slug: "course",
    content: "<div>Course fractionnée</div>",
  },
  {
    id: 3,
    title: "Course",
    tags: [WorkoutSubjectEnum.course, WorkoutSubjectEnum.debutant],
    slug: "course",
    content: "<div>Course fractionnée</div>",
  },
  {
    id: 4,
    title: "Course",
    tags: [WorkoutSubjectEnum.course, WorkoutSubjectEnum.debutant],
    slug: "course",
    content: "<div>Course fractionnée</div>",
  },
  {
    id: 5,
    title: "Course",
    tags: [WorkoutSubjectEnum.course, WorkoutSubjectEnum.debutant],
    slug: "course",
    content: "<div>Course fractionnée</div>",
  },
  {
    id: 6,
    title: "Course",
    tags: [WorkoutSubjectEnum.course, WorkoutSubjectEnum.debutant],
    slug: "course",
    content: "<div>Course fractionnée</div>",
  },
  {
    id: 7,
    title: "Course",
    tags: [WorkoutSubjectEnum.course, WorkoutSubjectEnum.debutant],
    slug: "course",
    content: "<div>Course fractionnée</div>",
  },
  {
    id: 8,
    title: "Course",
    tags: [WorkoutSubjectEnum.course, WorkoutSubjectEnum.debutant],
    slug: "course",
    content: "<div>Course fractionnée</div>",
  },
  {
    id: 9,
    title: "Course",
    tags: [WorkoutSubjectEnum.course, WorkoutSubjectEnum.debutant],
    slug: "course",
    content: "<div>Course fractionnée</div>",
  },
  {
    id: 10,
    title: "Course",
    tags: [WorkoutSubjectEnum.course, WorkoutSubjectEnum.debutant],
    slug: "course",
    content: "<div>Course fractionnée</div>",
  },
  {
    id: 11,
    title: "Course",
    tags: [WorkoutSubjectEnum.course, WorkoutSubjectEnum.debutant],
    slug: "course",
    content: "<div>Course fractionnée</div>",
  },
  {
    id: 12,
    title: "Course",
    tags: [WorkoutSubjectEnum.course, WorkoutSubjectEnum.debutant],
    slug: "course",
    content: "<div>Course fractionnée</div>",
  },
  {
    id: 13,
    title: "Course",
    tags: [WorkoutSubjectEnum.course, WorkoutSubjectEnum.debutant],
    slug: "course",
    content: "<div>Course fractionnée</div>",
  },
  {
    id: 14,
    title: "Course",
    tags: [WorkoutSubjectEnum.course, WorkoutSubjectEnum.debutant],
    slug: "course",
    content: "<div>Course fractionnée</div>",
  },
  {
    id: 15,
    title: "Course",
    tags: [WorkoutSubjectEnum.course, WorkoutSubjectEnum.debutant],
    slug: "course",
    content: "<div>Course fractionnée</div>",
  },
  {
    id: 16,
    title: "Course",
    tags: [WorkoutSubjectEnum.course, WorkoutSubjectEnum.debutant],
    slug: "course",
    content: "<div>Course fractionnée</div>",
  },
  {
    id: 17,
    title: "Course",
    tags: [WorkoutSubjectEnum.course, WorkoutSubjectEnum.debutant],
    slug: "course",
    content: "<div>Course fractionnée</div>",
  },
  {
    id: 18,
    title: "Course",
    tags: [WorkoutSubjectEnum.course, WorkoutSubjectEnum.debutant],
    slug: "course",
    content: "<div>Course fractionnée</div>",
  },
  {
    id: 19,
    title: "Course",
    tags: [WorkoutSubjectEnum.course, WorkoutSubjectEnum.debutant],
    slug: "course",
    content: "<div>Course fractionnée</div>",
  },
  {
    id: 20,
    title: "Course",
    tags: [WorkoutSubjectEnum.course, WorkoutSubjectEnum.debutant],
    slug: "course",
    content: "<div>Course fractionnée</div>",
  },
];
